FROM continuumio/anaconda3:5.3.0

RUN conda install -y h5py tensorflow-gpu keras
RUN apt-get update && apt-get install -y build-essential
RUN conda install -c conda-forge pytorch-pretrained-bert
RUN conda install -c fastai fastai
WORKDIR /work
